# Project information
site_name: Documentation
site_description: Documentation for Ebakus blockchain stuff.
site_url: https://docs.ebakus.com/
site_author: The Ebakus Team

# Repository
repo_name: ebakus/ebakus-docs
repo_url: https://github.com/ebakus/ebakus-docs/
edit_uri: edit/develop/docs/

# Copyright
copyright: 'Copyright &copy; 2019 ebakus - All rights reserved'

# Page tree
nav:
  - 'index.md'
  - Migrating your ERC-20 EBK to Native EBK for the mainnet: 'migrating-your-erc-20-ebk-to-native-ebk-for-the-mainnet.md'
  - Developing with ebakus:
    - Getting started: 'developing-applications-with-ebakus/gettting-started-with-ebakus-development.md'
    - External node endpoints: 'developing-applications-with-ebakus/external-node-endpoints.md'
    - Proof of Work (PoW): 'developing-applications-with-ebakus/proof-of-work.md'
    - Running a local testnet: 'developing-applications-with-ebakus/running-a-local-testnet.md'
    - Running a development node: 'developing-applications-with-ebakus/running-a-local-development-node.md'
    - System contract: 'developing-applications-with-ebakus/system-contract.md'
    - Quick guides:
      - Migrating your ethereum dApp: 'developing-applications-with-ebakus/quick-guides/migrating-your-ethereum-d-app-to-ebakus.md'
      - Using ebakusDB: 'developing-applications-with-ebakus/quick-guides/using-ebakus-db.md'
    - Ebakus development stack:
      - Ebakus node: 'developing-applications-with-ebakus/the-ebakus-development-stack/ebakus-node.md'
      - Ebakus wallet: 'developing-applications-with-ebakus/the-ebakus-development-stack/ebakus-wallet.md'
      - Wallet loader: 'developing-applications-with-ebakus/the-ebakus-development-stack/wallet-loader.md'
      - web3-ebakus: 'developing-applications-with-ebakus/the-ebakus-development-stack/web3-ebakus.md'
  - Becoming a Block Producer:
    - Introduction: 'becoming-a-block-producer/becoming-a-block-producer.md'
    - Running a full node as Witness: 'becoming-a-block-producer/running-a-witness.md'
    # - Hardening security: 'becoming-a-block-producer/hardening-security.md'
    # - Proposed specification: 'becoming-a-block-producer/proposed-specification.md'


# Configuration
theme:
  # https://github.com/squidfunk/mkdocs-material/tree/master/src
  name: 'material'
  custom_dir: themes/material/
  logo: 'img/logo.png'

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: black
    accent: pink
  font:
    text: Roboto
    code: Roboto Mono
#   favicon: assets/images/favicon.png
#   logo:
#     icon: "\uE80C"

use_directory_urls: true

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago

# Customization
extra:
  social:
    - type: globe
      link: https://www.ebakus.com/
    - type: github-alt
      link: https://github.com/ebakus
    - type: twitter
      link: https://twitter.com/EbakusNetwork
    - type: linkedin
      link: https://www.linkedin.com/company/ebakus-blockchain/
    - type: telegram
      link: https://t.me/ebakus

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - scripts/extra.js

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite
  - def_list
  # - meta
  - smarty
  - toc:
      permalink: True
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true

# google_analytics: ['', 'docs.ebakus.com']
